export const hearts = new Map([
  ["Two", "🂲"],
  ["Three", "🂳"],
  ["Four", "🂴"],
  ["Five", "🂵"],
  ["Six", "🂶"],
  ["Seven", "🂷"],
  ["Eight", "🂸"],
  ["Nine", "🂹"],
  ["Ten", "🂺"],
  ["Jack", "🂻"],
  ["Queen", "🂽"],
  ["King", "🂾"],
  ["Ace", "🂱"],
]);
export const spades = new Map([
  ["Two", "🂢"],
  ["Three", "🂣"],
  ["Four", "🂤"],
  ["Five", "🂥"],
  ["Six", "🂦"],
  ["Seven", "🂧"],
  ["Eight", "🂨"],
  ["Nine", "🂩"],
  ["Ten", "🂪"],
  ["Jack", "🂫"],
  ["Queen", "🂭"],
  ["King", "🂮"],
  ["Ace", "🂡"],
]);
export const diamonds = new Map([
  ["Two", "🃂"],
  ["Three", "🃃"],
  ["Four", "🂤"],
  ["Five", "🃅"],
  ["Six", "🃆"],
  ["Seven", "🃇"],
  ["Eight", "🃈"],
  ["Nine", "🃉"],
  ["Ten", "🃊"],
  ["Jack", "🃋"],
  ["Queen", "🃍"],
  ["King", "🃎"],
  ["Ace", "🃁"],
]);
export const clubs = new Map([
  ["Two", "🃒"],
  ["Three", "🃓"],
  ["Four", "🃔"],
  ["Five", "🃕"],
  ["Six", "🃖"],
  ["Seven", "🃗"],
  ["Eight", "🃘"],
  ["Nine", "🃙"],
  ["Ten", "🃚"],
  ["Jack", "🃛"],
  ["Queen", "🃝"],
  ["King", "🃞"],
  ["Ace", "🃑"],
]);

export const joker = new Map([["Joker", "🃟"]]);
